# Generated by Django 5.0 on 2024-01-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
                ('pdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
