# Generated by Django 5.0 on 2024-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pquantity',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
