# Generated by Django 5.0 on 2024-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbproject', '0002_product_pquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pquantity', models.CharField(max_length=5)),
                ('pcdate', models.DateField(auto_now_add=True)),
                ('pudate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
